//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/v/s/r/vsriva10/EEE591/HW2/starter-02/primitives/MapReduce.vp
//  Source template: MapReduce
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

// MapReduce.vp
// inKeyWidth (_GENESIS2_DECLARATION_PRIORITY_) = 40
//
// m>n
// inValueWidth (_GENESIS2_DECLARATION_PRIORITY_) = 8
//
// outKeyWidth (_GENESIS2_DECLARATION_PRIORITY_) = 40
//
// outValueWidth (_GENESIS2_DECLARATION_PRIORITY_) = 32
//
// addrWidth (_GENESIS2_DECLARATION_PRIORITY_) = 32
//



module MapReduce (
//For Mapper
	input enable, 
	input [31:0] task_id,
	input [39:0] key,
	input [7:0] value,
	input clk,
	input tail,
	input clear,
	output finish, 
	output read_request,
	output  write_request,
	output [39:0] int_key,
	output [31:0] int_value,
	output [31:0] read_addr,
	output [31:0] write_addr
/*
//For Reducer
	input enable, 
	input [31:0] task_id,
	input [39:0] int_key,
	input [39:0] search_key,
	input [31:0] int_value,
	input clk,
	output finish, 
	output read_request,
	output write_request,
	output [31:0] result,
	output [31:0] read_addr,
	output [31:0] write_addr
*/
);

//empty module
	MapReduceMapper_unq1  my_MapReduceMapper(.enable(enable), .task_id(task_id), .key(key), .value(value), .clk(clk), .clear(clear), .tail(tail), .finish(finish), .read_request(read_request), .write_request(write_request), .int_key(int_key), .int_value(int_value), .read_addr(read_addr), .write_addr(write_addr));
/*
	MapReduceReducer_unq1  my_MapReduceReducer(.enable(enable), .task_id(task_id), .int_key(int_key), .search_key(search_key), .int_value(int_value), .clk(clk), .finish(finish), .read_request(read_request), .write_request(write_request), .result(result), .read_addr(read_addr), .write_addr(write_addr));
*/
endmodule: MapReduce
	

			
